# Generated by Django 3.2.4 on 2021-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_completed', 'completed'), ('is_canceled', 'canceled'), ('is_pending', 'pending')], max_length=30),
        ),
    ]
